function [fitresult, gof] = sineFit(myTime, Pos1x)
%CREATEFITS(MYTIME,POS1X)
%  Create fits.
%
%  Data for 'untitled fit 1' fit:
%      X Input : myTime
%      Y Output: Pos1x
%  Data for 'sineFit' fit:
%      X Input : myTime
%      Y Output: Pos1x
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Feb-2012 20:49:33

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 2, 1 );
gof = struct( 'sse', cell( 2, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( myTime, Pos1x );

% Set up fittype and options.
ft = fittype( 'sin2' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf -Inf 0 -Inf];
opts.Robust = 'Bisquare';
opts.StartPoint = [94.6523879064382 0.00826723098340722 3.01854734687724 54.0063037859239 0.0165344619668144 -1.83184944230966];
opts.Upper = [Inf 3.15 6 Inf Inf Inf];

% Fit model to data.
[fitresult{1}, gof(1)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult{1}, xData, yData );
legend( h, 'Pos1x vs. myTime', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel( 'myTime' );
ylabel( 'Pos1x' );
grid on

%% Fit: 'sineFit'.
[xData, yData] = prepareCurveData( myTime, Pos1x );

% Set up fittype and options.
ft = fittype( 'sin1' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf];
opts.StartPoint = [39.806084459695 0.0306053364772554 0.231035526934143];
opts.Upper = [Inf Inf Inf];

% Fit model to data.
[fitresult{2}, gof(2)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'sineFit' );
h = plot( fitresult{2}, xData, yData );
legend( h, 'Pos1x vs. myTime', 'sineFit', 'Location', 'NorthEast' );
% Label axes
xlabel( 'myTime' );
ylabel( 'Pos1x' );
grid on


